name: Test LTSC 2022 Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering

jobs:
  test-ltsc2022:
    runs-on: windows-2022
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: List files in repository
      run: |
        Write-Host "Files in repository:" -ForegroundColor Yellow
        Get-ChildItem -Name
        
    - name: Verify test.ps1 exists
      run: |
        if (Test-Path "test.ps1") {
          Write-Host "✅ test.ps1 found" -ForegroundColor Green
        } else {
          Write-Host "❌ test.ps1 missing" -ForegroundColor Red
          exit 1
        }
        
    - name: Build Docker image
      run: |
        Write-Host "Building LTSC 2022 Docker image..." -ForegroundColor Yellow
        docker build -t ltsc2022-httpbin-test .
        
    - name: Run Docker container test
      run: |
        Write-Host "Running LTSC 2022 container test..." -ForegroundColor Yellow
        docker run --rm ltsc2022-httpbin-test
        
    - name: Test container interactively
      run: |
        Write-Host "Checking container contents..." -ForegroundColor Yellow
        docker run --rm ltsc2022-httpbin-test powershell -Command "Get-ChildItem C:\ | Where-Object Name -eq 'test.ps1'"
